config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :user
  resources :posts, only: %i[new create index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :author, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :author)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Kehinde</h1>

<% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <p>Welcome, <%= current_user.email %></p>
<% else %>
  <%= link_to "Log in", user_session_path, method: :post %>
  <p>Welcome, people from another dimension</p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <% if user_signed_in? %>
          <td><%= post.user.email %></td>
        <% else %>
          <td>Anonymous</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1> Create your post </h1>

<%= form_with(model: @post, url: posts_path, method: :post) do |form| %>
    <%= @post.errors.full_messages %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  
    <div class="field">
      <%= form.label :author %>
      <%= form.text_field :author %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<br>

<%= link_to "Log out", destroy_user_session_path, method: :delete %>